services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"

  serviceA:
    image: pietrzyckagata/rabbitmq-servicea:latest
    pull_policy: always
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
    depends_on: #define dependencies of this app
      - rabbitmq

  serviceB:
    image: pietrzyckagata/rabbitmq-serviceb:latest
    pull_policy: always
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
    depends_on: #define dependencies of this app
      - rabbitmq

  producer:
    image: pietrzyckagata/rabbitmq-producer:latest
    pull_policy: always
    ports:
      - "8083:8083"
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
    depends_on: #define dependencies of this app
      - rabbitmq